apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Pod","metadata":{"annotations":{},"labels":{"what":"what"},"name":"nginx","namespace":"default"},"spec":{"containers":[{"image":"nginx:1.7.9","name":"nginx","ports":[{"containerPort":80}]}]}}
  creationTimestamp: "2020-01-22T22:17:52Z"
  labels:
    app: web_service
    importance: critical
    customer: internal_use
    what: what
  name: nginx
  namespace: default
  resourceVersion: "298444"
  selfLink: /api/v1/namespaces/default/pods/nginx
  uid: 5dad9aaa-ecf8-4b8c-a63f-98cad3aa509d
spec:
  containers:
  - image: nginx:1.7.9
    imagePullPolicy: IfNotPresent
    name: nginx
    ports:
    - containerPort: 80
      protocol: TCP
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-phnpj
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: k8s-247-node-03
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: default-token-phnpj
    secret:
      defaultMode: 420
      secretName: default-token-phnpj
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2020-01-22T22:17:53Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2020-01-22T22:18:46Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2020-01-22T22:18:46Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2020-01-22T22:17:52Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://cef62288f98ab785d408cb90a2093f36c73e066760f39a4a9e84799cdac57ea3
    image: docker.io/library/nginx:1.7.9
    imageID: sha256:35d28df486f6150fa3174367499d1eb01f22f5a410afe4b9581ac0e0e58b3eaf
    lastState:
      terminated:
        containerID: containerd://dc49d794f61add830dba4aa048343968e2df4facb46c40b15a346cd11c27a857
        exitCode: 0
        finishedAt: "2020-01-22T22:18:44Z"
        reason: Completed
        startedAt: "2020-01-22T22:17:54Z"
    name: nginx
    ready: true
    restartCount: 1
    state:
      running:
        startedAt: "2020-01-22T22:18:45Z"
  hostIP: 10.4.74.136
  phase: Running
  podIP: 192.168.52.212
  qosClass: BestEffort
  startTime: "2020-01-22T22:17:53Z"
